### PR TITLE
Issue 526: Fix intermittently failing Kotlin tests.

### LINKED ISSUE #526: Intermittent functional test failures due to object database assertions
Some functional tests fail due to incorrect use of styx object database in assertions.

The affected tests have to following pattern:

- Poll for `/admin/routing/objects` endpoint for routing object changes.
- Once changes are detected, move on to a next step assuming routing object changes are in place.
- The next step fails because internally Styx has not yet converged to the latest database state.

### PR DESCRIPTION
**Pull request by mikkokar**
Fixes #526.

### CODE REVIEW

File: system-tests/ft-suite/src/test/kotlin/com/hotels/styx/providers/HealthCheckProviderSpec.kt [hunk 1]
```diff
@@ -117,9 +117,11 @@ class HealthCheckProviderSpec : FeatureSpec() {
                     styxServer().routingObject("aaa-02").get().shouldContain("state:inactive")
                 }
 
-                pollOrigins(styxServer, "origin-01", times = 50).let {
-                    withClue("Only the active origin (origin-01) should be taking traffic. Origins distribution: $it") {
-                        it["origin-01"]?:0.shouldBe(50)
+                eventually(2.seconds, AssertionError::class.java) {
+                    pollOrigins(styxServer, times = 50).let {
+                        withClue("Only the active origin (origin-01) should be taking traffic. Origins distribution: $it") {
+                            it["origin-01"] ?: 0.shouldBe(50)
```
Comment (chrisgresty) [inline system-tests/ft-suite/src/test/kotlin/com/hotels/styx/providers/HealthCheckProviderSpec.kt]: Please change this (and other similar usages) to `(it["origin-01"] ?: 0).shouldBe(50)`

Comment (mikkokar) [reply system-tests/ft-suite/src/test/kotlin/com/hotels/styx/providers/HealthCheckProviderSpec.kt]: Good catch! Fixed.
